const levels = [
  { title: 'Shop Safety', station: 'PPE Gate', color: '#ffc857', qs: [
    ['What protects your eyes from flying chips?', ['Safety glasses','Cotton gloves','Earbuds','Apron'],0,'Use rated eye protection whenever chips can fly.'],
    ['Before measuring a rotating part, you should…', ['Slow it slightly','Stop the machine','Hold the caliper tighter','Add coolant'],1,'Never measure a moving workpiece.'],
    ['Long hair near a lathe should be…', ['Wet','Tied and contained','Under the chuck','Brushed sideways'],1,'Contain hair and loose clothing before startup.'],
    ['The safest way to remove metal chips is…', ['Bare hand','Compressed air at your face','Chip brush','Shop rag on spindle'],2,'Use a brush or chip hook after motion stops.'],
    ['A chuck key should be removed…', ['Before startup','After the first cut','At lunch','Only on CNC machines'],0,'A key left in a chuck can become a projectile.'],
    ['Emergency-stop buttons are used for…', ['Normal shutdown','Immediate hazardous motion','Changing tools','Turning on coolant'],1,'Use E-stop for an immediate unsafe condition.'],
    ['Before servicing a powered machine, use…', ['Higher feed','Lockout/tagout','A longer wrench','Automatic mode'],1,'Isolate hazardous energy before service.'],
    ['Loose gloves near rotating spindles are…', ['Recommended','Unsafe','Required','A measuring aid'],1,'They can catch and pull a hand into rotation.'],
    ['A damaged grinding wheel should be…', ['Used slowly','Dressed harder','Removed from service','Cooled with oil'],2,'Cracked or damaged wheels may burst.'],
    ['Good housekeeping mainly prevents…', ['Accurate cuts','Slips, trips, and fires','Tool wear','Blueprint changes'],1,'Clean, dry walkways are a core shop control.'] ] },
  { title: 'Measurement', station: 'Inspection Bench', color: '#65d6ce', qs: [
    ['Which tool accurately measures an outside diameter?', ['Micrometer','Hammer','Center punch','Tap wrench'],0,'An outside micrometer is made for precise diameters.'],
    ['0.500 inch equals…', ['One quarter','One half','Five inches','Five thousandths'],1,'0.500 is one-half inch.'],
    ['A tolerance of ±0.002 allows a total range of…', ['0.002','0.004','0.020','0.040'],1,'Two thousandths above plus two below is four total.'],
    ['A caliper should be zeroed…', ['After every answer','Before measuring','Only when new','Against a rough casting'],1,'Close clean jaws and verify zero first.'],
    ['A 20 mm diameter has what radius?', ['5 mm','10 mm','20 mm','40 mm'],1,'Radius is half the diameter.'],
    ['The symbol Ø means…', ['Radius','Diameter','Depth','Angle'],1,'Ø identifies a diameter dimension.'],
    ['Which gauge checks a small gap?', ['Feeler gauge','Ring gauge','Height gauge','Pressure gauge'],0,'Feeler leaves have known thicknesses.'],
    ['1 inch is exactly…', ['10 mm','20 mm','25.4 mm','30.48 mm'],2,'The exact conversion is 25.4 millimeters.'],
    ['A datum is…', ['Scrap stock','Reference for measurement','Cutting fluid','A drill point'],1,'Datums anchor dimensions and inspection.'],
    ['If a bore reads 25.03 mm and max is 25.02, it is…', ['In tolerance','Oversize','Undersize','Exactly nominal'],1,'It exceeds the maximum by 0.01 mm.'] ] },
  { title: 'Drilling & Bores', station: 'Drill Dock', color: '#ff7f66', qs: [
    ['For a 12 mm finished bore, the radius is…', ['3 mm','6 mm','12 mm','24 mm'],1,'Radius = diameter ÷ 2.'],
    ['A center drill helps prevent…', ['Coolant flow','Drill wandering','Thread fit','Weld spatter'],1,'It creates a precise starting seat.'],
    ['A larger drill generally needs…', ['Higher RPM','Lower RPM','No clamping','Reverse feed'],1,'Surface speed requires RPM to fall as diameter grows.'],
    ['Before drilling, the workpiece must be…', ['Hand held','Clamped','Painted','Heated red'],1,'Secure clamping prevents spinning or lifting.'],
    ['Cutting fluid can reduce…', ['Tool life','Heat and friction','Hole depth','Machine weight'],1,'Lubrication and cooling protect tool and finish.'],
    ['A reamer is normally used to…', ['Start rough stock','Finish a hole accurately','Cut external threads','Bend sheet'],1,'Reaming sizes and improves a predrilled hole.'],
    ['A 10 mm drill at 30 m/min needs closest RPM?', ['95','955','9550','30'],1,'RPM ≈ (1000×30)/(π×10) ≈ 955.'],
    ['Peck drilling helps…', ['Pack chips','Clear deep-hole chips','Increase runout','Remove clamps'],1,'Periodic withdrawal breaks and clears chips.'],
    ['A countersink creates…', ['A conical seat','Internal threads','A square hole','A weld bead'],0,'It seats flat-head fasteners.'],
    ['The web of a twist drill is at its…', ['Outer corner','Center core','Flute end only','Shank label'],1,'The web is the central material joining the flutes.'] ] },
  { title: 'Lathe', station: 'Turning Line', color: '#9b8cff', qs: [
    ['On a lathe, the primary rotating item is the…', ['Cutting tool','Workpiece','Tailstock','Carriage handwheel'],1,'Turning rotates the work against the tool.'],
    ['Facing makes the end…', ['Flat and square','Threaded','Knurled only','Hollow automatically'],0,'Facing cuts across the end face.'],
    ['Turning from 30 mm to 26 mm removes how much per side?', ['1 mm','2 mm','4 mm','8 mm'],1,'Diameter drops 4 mm, so radial depth is 2 mm.'],
    ['The tailstock can support work with a…', ['Center','Vise','Brake','Torch'],0,'A center supports long rotating work.'],
    ['Parting is used to…', ['Separate a part','Measure a bore','Weld a seam','Harden steel'],0,'A narrow tool cuts the finished part from stock.'],
    ['Knurling produces…', ['A grip texture','A mirror bore','A weld joint','A gear ratio'],0,'Knurl wheels press a patterned grip into the surface.'],
    ['Excessive tool overhang tends to cause…', ['Chatter','Stronger cuts','Zero heat','Larger chuck'],0,'Short, rigid setups resist vibration.'],
    ['CSS on a CNC lathe means…', ['Constant surface speed','Coolant safety switch','Center spindle stop','Cut size standard'],0,'RPM changes to maintain surface speed.'],
    ['A boring bar cuts…', ['An internal diameter','Only an outside thread','Sheet metal','A weld groove'],0,'Boring enlarges and finishes an existing hole.'],
    ['Before reversing a manual spindle, first…', ['Stop it','Add a glove','Open the guard','Strike the chuck'],0,'Stop before changing rotation direction.'] ] },
  { title: 'Milling', station: 'Mill Platform', color: '#56b4ff', qs: [
    ['On a mill, the primary rotating item is the…', ['Workpiece','Cutting tool','Table','Vise'],1,'The spindle rotates the cutter.'],
    ['Conventional and climb describe…', ['Milling direction','Weld polarity','Drill material','Inspection light'],0,'They describe feed direction relative to cutter rotation.'],
    ['An end mill can commonly cut with…', ['Its end and sides','Its shank only','A torch flame','A brake die'],0,'End mills have cutting edges on end and periphery.'],
    ['A vise should be indicated when…', ['Aligning it to machine travel','Painting it','Changing coolant','Reading RPM'],0,'Indicating makes the fixed jaw parallel to an axis.'],
    ['Chip load is feed per…', ['Tooth','Hour','Machine','Liter'],0,'Each tooth should remove a controlled chip thickness.'],
    ['A 4-flute cutter at 1000 RPM and .05 mm/tooth feeds at…', ['50 mm/min','100','200','400'],2,'Feed = 4×1000×0.05 = 200 mm/min.'],
    ['An edge finder locates…', ['A workpiece edge','A weld leak','Oil pressure','Thread pitch'],0,'It establishes a coordinate edge.'],
    ['A pocket is…', ['An enclosed recessed feature','A raised boss only','A thread gauge','A safety guard'],0,'Pocketing removes material inside a boundary.'],
    ['Tramming a mill aligns the spindle to the…', ['Table','Floor color','Coolant tank','Tool cart'],0,'Tram makes the spindle perpendicular to the table.'],
    ['A roughing pass is followed by a…', ['Finishing pass','Power outage','Weld pass','Lockout only'],0,'Leave controlled stock, then finish to size and surface.'] ] },
  { title: 'CNC Programming', station: 'Code Console', color: '#42e38c', qs: [
    ['G00 commands…', ['Rapid positioning','Linear cutting feed','Clockwise arc','Tool change'],0,'G00 moves rapidly between cutting positions.'],
    ['G01 commands…', ['Linear feed move','Spindle stop','Coolant off','Home only'],0,'G01 cuts a straight line at programmed feed.'],
    ['M03 usually starts the spindle…', ['Clockwise','Counterclockwise','At zero RPM','Without a tool'],0,'M03 is the common clockwise spindle command.'],
    ['M05 usually…', ['Stops spindle','Starts coolant','Calls tool 5','Cuts an arc'],0,'M05 commands spindle stop.'],
    ['G90 selects…', ['Absolute coordinates','Incremental only','Rapid only','Metric automatically'],0,'Positions are measured from the active origin.'],
    ['G91 selects…', ['Incremental coordinates','Absolute coordinates','Tool length','Workholding'],0,'Moves are measured from the current position.'],
    ['A dry run is intended to…', ['Check motion safely','Cut faster','Ignore offsets','Disable guards'],0,'Prove the path with controlled, cautious execution.'],
    ['A work offset defines…', ['Part coordinate origin','Motor voltage','Weld current','Tool hardness'],0,'It connects drawing coordinates to the setup.'],
    ['Tool length compensation accounts for…', ['Different tool lengths','Stock color','Operator height','Coolant depth'],0,'The control adjusts Z for each measured tool.'],
    ['Single block mode executes…', ['One program block at a time','All tools together','Only comments','One part per week'],0,'It is valuable during prove-out.'] ] },
  { title: 'Threads & Fasteners', station: 'Thread Works', color: '#f89de2', qs: [
    ['A tap cuts…', ['Internal threads','External threads','A flat face','A weld bead'],0,'Taps form or cut female threads.'],
    ['A die cuts…', ['External threads','Internal bores only','Keyways','Sheet bends'],0,'Dies commonly cut male threads.'],
    ['Thread pitch is the distance between…', ['Adjacent crests','Bolt head flats','Two machines','Drill flutes'],0,'Pitch is measured crest to crest.'],
    ['The tap drill must normally be…', ['Smaller than major diameter','Larger than bolt head','Exactly zero','Square'],0,'It leaves material for the thread.'],
    ['A bottoming tap is useful near…', ['The bottom of a blind hole','A sheet edge','A welding ground','A lathe belt'],0,'Its short chamfer reaches closer to the bottom.'],
    ['Cross-threading means threads are…', ['Misaligned and damaged','Perfectly fitted','Heat treated','Left handed'],0,'Stop and realign instead of forcing the fastener.'],
    ['A torque specification controls…', ['Fastener preload','Paint shade','Tool RPM only','Hole radius'],0,'Correct torque helps produce intended clamping force.'],
    ['A left-hand thread tightens…', ['Counterclockwise','Clockwise','Either direction','With no rotation'],0,'It uses the opposite hand from standard threads.'],
    ['A thread gauge identifies…', ['Pitch','Voltage','Surface hardness','Weld gas'],0,'Its leaves match known thread pitches.'],
    ['Deburring a tapped hole helps…', ['Assembly and safe handling','Increase runout','Hide cracks','Reverse pitch'],0,'Remove sharp raised edges without damaging threads.'] ] },
  { title: 'Welding & Fabrication', station: 'Fabrication Bay', color: '#ff9f43', qs: [
    ['A welding helmet primarily protects the…', ['Eyes and face','Boot soles','Machine table','Gas bottle valve'],0,'It shields against arc radiation and spatter.'],
    ['The ground/work clamp completes the…', ['Welding circuit','Blueprint','Air line','Thread pitch'],0,'Current must return through a sound connection.'],
    ['Porosity is often caused by…', ['Contamination or poor shielding','Perfect cleaning','Correct gas flow','Accurate fit-up'],0,'Oil, rust, moisture, wind, or gas problems trap pores.'],
    ['Tack welds are used first to…', ['Hold alignment','Finish paint','Cut plate','Measure voltage'],0,'Tacks preserve fit-up before final welds.'],
    ['A press brake primarily…', ['Bends sheet or plate','Turns shafts','Drills bores','Cuts threads'],0,'Matched tooling forms controlled bends.'],
    ['Bend allowance accounts for…', ['Material length through a bend','Weld color','Drill RPM','Bolt torque'],0,'The neutral-axis arc consumes part of flat length.'],
    ['A fillet weld joins surfaces commonly at…', ['An angle','The same bore','A thread crest','A spindle taper only'],0,'Fillets are common in lap, tee, and corner joints.'],
    ['Heat distortion is reduced by…', ['Balanced sequence and restraint','One huge hot pass','Dirty metal','Extra gap everywhere'],0,'Manage heat input and sequence.'],
    ['Before hot work near combustibles, you should…', ['Remove/protect them and follow permit rules','Add oxygen','Ignore sparks','Use paper shields'],0,'Control ignition hazards and maintain fire watch as required.'],
    ['A shear is designed to…', ['Cut sheet metal','Bore cylinders','Turn threads','Measure angles'],0,'Shearing separates material with opposing blades.'] ] },
  { title: 'Quality & Troubleshooting', station: 'Quality Lab', color: '#7bd389', qs: [
    ['Runout describes…', ['Variation during rotation','Thread depth only','Paint thickness','Weld gas flow'],0,'An indicator measures wobble relative to an axis.'],
    ['Chatter marks suggest…', ['Vibration','Perfect rigidity','No tool contact','Correct finish'],0,'Check rigidity, speed, feed, and tool condition.'],
    ['A dimension trending larger each part may indicate…', ['Tool wear or thermal growth','A sharper new tool','No process change','A cleaner floor'],0,'Trends should trigger adjustment before scrap.'],
    ['First-piece inspection occurs…', ['Before full production','After shipping','Only after scrap','Before reading print'],0,'Validate setup before committing the batch.'],
    ['A control chart helps detect…', ['Process variation over time','Part color only','Machine brand','Employee schedule'],0,'It distinguishes trends and unusual variation.'],
    ['If a tool suddenly sounds wrong, first…', ['Pause safely and inspect','Increase feed','Reach into motion','Ignore it'],0,'Unexpected sound can warn of failure or collision.'],
    ['A burr is…', ['Unwanted raised material at an edge','A precision datum','A coolant pump','A thread form'],0,'Deburr without altering the required geometry.'],
    ['Surface finish can worsen from a…', ['Dull tool','Rigid setup','Correct feed','Clean taper'],0,'A worn edge rubs or tears instead of shearing cleanly.'],
    ['Traceability connects a part to…', ['Material and process records','Only its paint','An unrelated machine','A game score only'],0,'Records support quality and root-cause work.'],
    ['Root-cause correction should prevent…', ['Recurrence','Measurement','Training','Documentation'],0,'Fix the system cause, not merely the symptom.'] ] },
  { title: 'Production Mastery', station: 'Final Assembly', color: '#ffd166', qs: [
    ['A router sheet defines…', ['Operation sequence','Internet settings','Only part color','Employee lunch'],0,'It guides the part through its planned process.'],
    ['Cycle time is…', ['Time to complete a production cycle','Tool diameter','Material hardness','Inspection tolerance'],0,'It supports capacity and flow planning.'],
    ['A bottleneck is the step that…', ['Limits total throughput','Always runs fastest','Uses no labor','Has the brightest light'],0,'Improving non-bottlenecks may not raise output.'],
    ['Poka-yoke means…', ['Mistake-proofing','Faster spindle','Larger tolerance','Hidden rework'],0,'Design the process so errors are prevented or obvious.'],
    ['Standard work records the…', ['Best current safe repeatable method','Operator nickname','Machine color','Scrap price only'],0,'It creates a baseline for training and improvement.'],
    ['A kitted assembly contains…', ['Needed parts grouped for the job','Random leftovers','Only cutting tools','No documentation'],0,'Kitting reduces searching and missing components.'],
    ['Preventive maintenance is scheduled to…', ['Reduce unexpected failure','Create breakdowns','Avoid lubrication','Change drawings'],0,'Planned care protects reliability and accuracy.'],
    ['OEE combines availability, performance, and…', ['Quality','Paint','Wages','Floor area'],0,'OEE highlights major production losses.'],
    ['Before releasing a finished assembly, verify…', ['Function, dimensions, and records','Only its weight','Only its color','Nothing if it fits'],0,'Release requires documented conformance.'],
    ['The strongest production habit is…', ['Safe, measured continuous improvement','Skipping checks','Hiding errors','Running damaged tools'],0,'Build quality through disciplined learning.'] ] }
];

export const QUESTIONS = levels.flatMap((level, li) => level.qs.map((q, qi) => ({
  id: li * 10 + qi + 1, level: li + 1, title: level.title, station: level.station,
  color: level.color, prompt: q[0], options: q[1], answer: q[2], explanation: q[3]
})));

export const LEVELS = levels.map((l, i) => ({ id:i+1, title:l.title, station:l.station, color:l.color }));

export const CHALLENGES = [
  { title:'Safety setup', prompt:'Tap every item required before spindle start.', items:['Eye protection','Chuck key removed','Work clamped','Loose glove'], correct:[0,1,2] },
  { title:'Inspect the shaft', prompt:'The print calls for Ø20.00 ±0.02 mm. Choose the passing measurement.', items:['19.97 mm','20.01 mm','20.03 mm'], correct:[1] },
  { title:'Choose the drill', prompt:'A 12 mm bore needs a 6 mm radius. Select the correct diameter drill for a rough 11.8 mm hole.', items:['6 mm','11.8 mm','24 mm'], correct:[1] },
  { title:'Turn the shaft', prompt:'Reduce Ø30 to Ø26. Choose radial depth of cut.', items:['1 mm','2 mm','4 mm'], correct:[1] },
  { title:'Set chip feed', prompt:'4 flutes × 1000 RPM × 0.05 mm/tooth.', items:['50 mm/min','200 mm/min','400 mm/min'], correct:[1] },
  { title:'Prove the CNC', prompt:'Choose the safest first proving mode.', items:['Rapid at 100%','Single block + low rapid','Ignore offsets'], correct:[1] },
  { title:'Tap the hole', prompt:'Choose the tool that creates an internal thread.', items:['Die','Tap','Reamer'], correct:[1] },
  { title:'Build the bracket', prompt:'Choose the machine used to make the 90° sheet bend.', items:['Press brake','Lathe','Surface grinder'], correct:[0] },
  { title:'Find the fault', prompt:'Repeating waves appear on the turned finish. Diagnose it.', items:['Chatter','Perfect cut','Porosity'], correct:[0] },
  { title:'Release the assembly', prompt:'Choose every final-release requirement.', items:['Function test','Dimension check','Traceability record','Hide rework'], correct:[0,1,2] }
];
